/*
 * @(#)MaquinaDeEstadosFrame.java	1.0 31/04/2004
 *
 * Copyleft (L) 2004 Laboratório de Arquitetura e Redes de Computadores
 * Escola Politécnica da Universidade de São Paulo.
 *
 */
package br.usp.larc.tcp.aplicacao;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.border.TitledBorder;

import br.usp.larc.tcp.protocolo.Decoder;
import br.usp.larc.tcp.protocolo.MaquinaDeEstados;
import br.usp.larc.tcp.protocolo.TCP;

/** 
 * Classe que representa a Interface HM Maquina de Estados.
 * Detalhes e dicas de implementação podem ser consultadas nas Apostilas.
 *
 * Procure sempre usar o paradigma Orientado a Objeto, a simplicidade e a 
 * criatividade na implementação do seu projeto.
 *  
 *
 * @author	Laboratório de Arquitetura e Redes de Computadores.
 * @version	1.0 Agosto 2003.
 */
/**
 * @author acdcp
 */
public class MaquinaDeEstadosFrame extends javax.swing.JFrame {
    
    /** Creates new form MaquinaDeEstadosFrame */
//    public MaquinaDeEstadosFrame() {
//        initComponents();
//    }
    
    /**
     * Creates new form Monitor
     * 
     * @param _maquinaDeEstados
     */
    public MaquinaDeEstadosFrame (MaquinaDeEstados _maquinaDeEstados)
    {
        this.maquinaDeEstados = _maquinaDeEstados;
        this.initComponents ();
        this.setSize (590, 550);
        this.idConexao = _maquinaDeEstados.getIdConexao ();
        this.setTitle ("Máquina de Estado " + this.idConexao + " (IPSimul = "
                       + this.maquinaDeEstados.getIpSimuladoLocalBytePonto () + " : "
                       + this.maquinaDeEstados.getPortaLocal () + ")");
        this.jtfHost.setText(this.maquinaDeEstados.getIpSimuladoLocalBytePonto ());
        this.setVisible (true);
    }

    
    /**
     * @param _flag
     */
    public void habilitaNovaConexao (boolean _flag)
    {
        /*
        if (_flag)
        {
            this.jlTitulo2.setForeground (new java.awt.Color (0, 153, 0));
            this.jlTitulo2.setHorizontalAlignment (javax.swing.SwingConstants.CENTER);
            this.jlTitulo2.setText ("Ativado");
        }
        else
        {
            this.jlTitulo2.setForeground (new java.awt.Color (204, 0, 0));
            this.jlTitulo2.setHorizontalAlignment (javax.swing.SwingConstants.CENTER);
            this.jlTitulo2.setText ("Desativado");
        }
        */

        this.jbActiveOpen.setEnabled (_flag);
        this.jbPassiveOpen.setEnabled (_flag);
        this.jtfPorta.setEditable (_flag);
        this.jtfHost.setEditable (_flag);

        this.jbEnviar.setEnabled (!_flag);
        this.jbClose.setEnabled (!_flag);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()
    {
        this.jpConexao = new JPanel ();
        this.jlInformacoesConexao = new JLabel ();
        this.jpPrimitivas = new javax.swing.JPanel ();
        this.jbActiveOpen = new javax.swing.JButton ();
        this.jbPassiveOpen = new javax.swing.JButton ();
        this.jbEnviar = new javax.swing.JButton ();
        this.jbClose = new javax.swing.JButton ();
        this.jlHost = new javax.swing.JLabel ();
        this.jlPorta = new javax.swing.JLabel ();
        this.jtfHost = new javax.swing.JTextField ();
        this.jtfPorta = new javax.swing.JTextField ();
        this.jlDadosEnviados = new javax.swing.JLabel ();
        this.jlNumBytesEnviados = new javax.swing.JLabel ();
        this.jspadosEnviados = new javax.swing.JScrollPane ();
        this.jtaDadosEnviados = new javax.swing.JTextArea ();
        this.jpDiagramaTempo = new javax.swing.JPanel ();
        this.jlEstado = new javax.swing.JLabel ();
        this.jlPrimitiva = new javax.swing.JLabel ();
        this.jlSentido = new javax.swing.JLabel ();
        this.jlSegmento = new javax.swing.JLabel ();
        this.jspEstado = new javax.swing.JScrollPane (null, ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        this.jtaEstado = new javax.swing.JTextArea ();
        this.jspPrimitiva = new javax.swing.JScrollPane (null, ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        this.jtaPrimitiva = new javax.swing.JTextArea ();
        this.jspSentido = new javax.swing.JScrollPane (null, ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        this.jtaSentido = new javax.swing.JTextArea ();
        this.jspDescricaoSegmento = new javax.swing.JScrollPane (null, ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        this.jtaDescricaoSegmento = new javax.swing.JTextArea ();
        this.jpConf = new javax.swing.JPanel ();
        this.jButtonAjuda = new javax.swing.JButton ();
        this.jbReset = new javax.swing.JButton ();
        this.jlTimeout = new javax.swing.JLabel ();
        this.jlTamJan = new javax.swing.JLabel ();
        this.jlTamSeg = new javax.swing.JLabel ();
        this.jtfTimeout = new javax.swing.JTextField ();
        this.jtfTamJan = new javax.swing.JTextField ();
        this.jtfTamSeg = new javax.swing.JTextField ();
        this.jpInfo = new javax.swing.JPanel ();
        this.jlEstAtual = new javax.swing.JLabel ();
        this.jlNumSeq = new javax.swing.JLabel ();
        this.jlNumACK = new javax.swing.JLabel ();
        this.jtfNumSeq = new javax.swing.JTextField ();
        this.jtfEstAtual = new javax.swing.JTextField ();
        this.jtfNumACK = new javax.swing.JTextField ();
        this.jpDadosRecebidos = new javax.swing.JPanel ();
        this.jspDadosRecebidos = new javax.swing.JScrollPane ();
        this.jtaDadosRecebidos = new javax.swing.JTextArea ();
        this.jpTudo = new javax.swing.JPanel ();
        this.jlRodape = new javax.swing.JLabel ();

        getContentPane().setLayout(null);

        setResizable(false);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                exitForm(evt);
            }
        });

        this.jpConexao.setLayout(null);

        this.jpConexao.setBorder(new TitledBorder(new EtchedBorder(), "Conexão", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Microsoft Sans Serif", 0, 12), Color.red));
        this.jlInformacoesConexao.setFont(new Font("Microsoft Sans Serif", 0, 10));
        this.jpConexao.add(this.jlInformacoesConexao);
        this.jlInformacoesConexao.setBounds(10, 20, 350, 30);

        getContentPane().add(this.jpConexao);
        this.jpConexao.setBounds(5, 0, 370, 60);

        this.jpPrimitivas.setLayout(null);

        this.jpPrimitivas.setBorder (new TitledBorder (new EtchedBorder (), "Primitivas",
                TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font (
                        "Microsoft Sans Serif", 0, 12), Color.red));
        this.jbActiveOpen.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jbActiveOpen.setText("ActiveOpen");
        this.jbActiveOpen.setBorder(new BevelBorder(BevelBorder.RAISED));
        this.jbActiveOpen.setHorizontalTextPosition(SwingConstants.CENTER);
        this.jbActiveOpen.setMargin(new Insets(2, 2, 2, 2));
        this.jbActiveOpen.setEnabled(true);
        this.jpPrimitivas.add(this.jbActiveOpen);
        this.jbActiveOpen.setBounds(10, 20, 80, 30);
        this.jbActiveOpen.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbActiveOpenActionPerformed(evt);
            }
        });
        
        this.jbPassiveOpen.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jbPassiveOpen.setText("PassiveOpen");
        this.jbPassiveOpen.setMaximumSize(new Dimension(500, 500));
        this.jbPassiveOpen.setBorder(new BevelBorder(BevelBorder.RAISED));
        this.jbPassiveOpen.setHorizontalTextPosition(SwingConstants.CENTER);
        this.jbPassiveOpen.setEnabled(true);
        this.jpPrimitivas.add(this.jbPassiveOpen);
        this.jbPassiveOpen.setBounds(10, 60, 100, 30);
        this.jbPassiveOpen.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbPassiveOpenActionPerformed(evt);
            }
        });

        this.jbEnviar.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jbEnviar.setText("Enviar");
        this.jbEnviar.setEnabled(false);
        this.jbEnviar.setBorder(new BevelBorder(BevelBorder.RAISED));
        this.jbEnviar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });
        this.jpPrimitivas.add(this.jbEnviar);
        this.jbEnviar.setBounds(140, 60, 100, 30);

        this.jbClose.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jbClose.setText("Close");
        this.jbClose.setEnabled(false);
        this.jbClose.setBorder(new BevelBorder(BevelBorder.RAISED));
        this.jbClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });
        this.jpPrimitivas.add(this.jbClose);
        this.jbClose.setBounds(260, 60, 100, 30);

        this.jlHost.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlHost.setText("Host");
        this.jpPrimitivas.add(this.jlHost);
        this.jlHost.setBounds(100, 20, 30, 15);

        this.jlPorta.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlPorta.setText("Porta");
        this.jpPrimitivas.add(this.jlPorta);
        this.jlPorta.setBounds(290, 20, 30, 16);
/*
        this.jTextFieldHost.addActionListener(new Listener() {
            public void actionPerformed(this.ActionEvent evt) {
                this.jTextFieldHostActionPerformed(evt);
            }
        });*/
        this.jpPrimitivas.add(this.jtfHost);
        this.jtfHost.setBounds(130, 20, 160, 20);
/*
        this.jTextFieldPorta.addActionListener(new Listener() {
            public void actionPerformed(this.ActionEvent evt) {
                this.jTextFieldPortaActionPerformed(evt);
            }
        });*/
        this.jpPrimitivas.add(this.jtfPorta);
        this.jtfPorta.setBounds(320, 20, 40, 20);

        this.jlDadosEnviados.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlDadosEnviados.setText("Dados Enviados");
        this.jpPrimitivas.add(this.jlDadosEnviados);
        this.jlDadosEnviados.setBounds(10, 90, 100, 15);

        this.jlNumBytesEnviados.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlNumBytesEnviados.setText("Número de byres enviados: 0");
        this.jpPrimitivas.add(this.jlNumBytesEnviados);
        this.jlNumBytesEnviados.setBounds(140, 90, 180, 15);

        this.jspadosEnviados.setViewportView(this.jtaDadosEnviados);

        this.jpPrimitivas.add(this.jspadosEnviados);
        this.jspadosEnviados.setBounds(10, 104, 350, 80);

        getContentPane().add(this.jpPrimitivas);
        this.jpPrimitivas.setBounds(5, 60, 370, 190);

        this.jpDiagramaTempo.setLayout(null);

        this.jpDiagramaTempo.setBorder(new TitledBorder(new EtchedBorder(), "Diagrama de Tempo", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Microsoft Sans Serif", 0, 12), Color.red));
        this.jlEstado.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlEstado.setText("Estado");
        this.jpDiagramaTempo.add(this.jlEstado);
        this.jlEstado.setBounds(10, 20, 45, 15);

        this.jlPrimitiva.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlPrimitiva.setText("Primitiva");
        this.jpDiagramaTempo.add(this.jlPrimitiva);
        this.jlPrimitiva.setBounds(100, 20, 60, 15);

        this.jlSentido.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlSentido.setText("Sentido");
        this.jpDiagramaTempo.add(this.jlSentido);
        this.jlSentido.setBounds(179, 20, 60, 15);

        this.jlSegmento.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlSegmento.setText("Seg.(NS,Tam,NACK,Jan)");
        this.jpDiagramaTempo.add(this.jlSegmento);
        this.jlSegmento.setBounds(225, 20, 140, 16);

        this.jtaEstado.setEditable(false);
        this.jspEstado.setViewportView(this.jtaEstado);
        this.jspEstado.setBounds(10, 40, 90, 200);
        this.jpDiagramaTempo.add(this.jspEstado);

//        this.jtaEstado.setBounds(10,40,90,200);
//        this.jtaEstado.setAlignmentY(0.0F);
//        this.jPanel3.add(this.jtaEstado);

        this.jtaPrimitiva.setEditable(false);
        this.jspPrimitiva.setViewportView(this.jtaPrimitiva);
        this.jspPrimitiva.setBounds(100, 40, 80, 200);
        this.jpDiagramaTempo.add(this.jspPrimitiva);

        this.jtaSentido.setFont(new Font("Monospaced", 0, 12));
        this.jtaSentido.setEditable(false);
        this.jspSentido.setViewportView(this.jtaSentido);
        this.jspSentido.setBounds(180, 40, 40, 200);
        this.jpDiagramaTempo.add(this.jspSentido);

        this.jtaDescricaoSegmento.setEditable(false);
        this.jspDescricaoSegmento.setViewportView(this.jtaDescricaoSegmento);
        this.jspDescricaoSegmento.setBounds(220, 40, 140, 200);
        this.jpDiagramaTempo.add(this.jspDescricaoSegmento);

        getContentPane().add(this.jpDiagramaTempo);
        this.jpDiagramaTempo.setBounds(5, 250, 370, 250);

        this.jpConf.setLayout(null);

        this.jpConf.setBorder(new TitledBorder(new EtchedBorder(), "Configura\u00e7\u00f5es", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Microsoft Sans Serif", 0, 12), Color.red));
        this.jButtonAjuda.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jButtonAjuda.setText("Ajuda");
        this.jButtonAjuda.setBorder(new BevelBorder(BevelBorder.RAISED));
        this.jpConf.add(this.jButtonAjuda);
        this.jButtonAjuda.setBounds(10, 110, 80, 20);

        this.jbReset.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jbReset.setText("Reset");
        this.jbReset.setBorder(new BevelBorder(BevelBorder.RAISED));
        this.jbReset.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbResetActionPerformed(evt);
            }
        });

        this.jpConf.add(this.jbReset);
        this.jbReset.setBounds(120, 110, 70, 20);

        this.jlTimeout.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlTimeout.setText("Timeout (ms):");
        this.jpConf.add(this.jlTimeout);
        this.jlTimeout.setBounds(10, 20, 130, 15);

        this.jlTamJan.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlTamJan.setText("Tam. Jan. (bytes):");
        this.jpConf.add(this.jlTamJan);
        this.jlTamJan.setBounds(10, 50, 130, 15);

        this.jlTamSeg.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlTamSeg.setText("Tam. Seg (bytes):");
        this.jpConf.add(this.jlTamSeg);
        this.jlTamSeg.setBounds(10, 80, 130, 15);

        this.jtfTimeout.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextFieldTimeoutActionPerformed(evt);
            }
        });

        this.jpConf.add(this.jtfTimeout);
        this.jtfTimeout.setText("3000");
        this.jtfTimeout.setBounds(140, 20, 50, 20);

        this.jpConf.add(this.jtfTamJan);
        this.jtfTamJan.setText("300");
        this.jtfTamJan.setBounds(140, 50, 50, 20);

        this.jpConf.add(this.jtfTamSeg);
        this.jtfTamSeg.setText("100");
        this.jtfTamSeg.setBounds(140, 80, 50, 20);

        getContentPane().add(this.jpConf);
        this.jpConf.setBounds(380, 0, 200, 140);

        this.jpInfo.setLayout(null);

        this.jpInfo.setBorder(new TitledBorder(new EtchedBorder(), "Informa\u00e7\u00f5es", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Microsoft Sans Serif", 0, 12), Color.red));
        this.jlEstAtual.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlEstAtual.setText("Est Atual (Tx/Rx)");
        this.jpInfo.add(this.jlEstAtual);
        this.jlEstAtual.setBounds(10, 20, 130, 15);

        this.jlNumSeq.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlNumSeq.setText("Nº Seq/Ult Conf");
        this.jpInfo.add(this.jlNumSeq);
        this.jlNumSeq.setBounds(10, 50, 130, 15);

        this.jlNumACK.setFont(new Font("Microsoft Sans Serif", 0, 12));
        this.jlNumACK.setText("Nº ACK");
        this.jpInfo.add(this.jlNumACK);
        this.jlNumACK.setBounds(10, 80, 130, 15);

        this.jpInfo.add(this.jtfNumSeq);
        this.jtfNumSeq.setBounds(140, 50, 50, 20);

        this.jtfEstAtual.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextFieldEstAtualActionPerformed(evt);
            }
        });

        this.jpInfo.add(this.jtfEstAtual);
        this.jtfEstAtual.setBounds(140, 20, 50, 20);

        this.jpInfo.add(this.jtfNumACK);
        this.jtfNumACK.setBounds(140, 80, 50, 20);

        getContentPane().add(this.jpInfo);
        this.jpInfo.setBounds(380, 140, 200, 110);

        this.jpDadosRecebidos.setLayout(null);

        this.jpDadosRecebidos.setBorder(new TitledBorder(new EtchedBorder(), "Dados Recebidos", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Microsoft Sans Serif", 0, 12), Color.red));
        this.jspDadosRecebidos.setViewportView(this.jtaDadosRecebidos);

        this.jpDadosRecebidos.add(this.jspDadosRecebidos);
        this.jspDadosRecebidos.setBounds(10, 20, 180, 220);

        getContentPane().add(this.jpDadosRecebidos);
        this.jpDadosRecebidos.setBounds(380, 250, 200, 250);

        this.jlRodape.setForeground(new Color(51, 51, 255));
        this.jlRodape.setText("MEFrame - Powered by Java Technologies - Copyleft (L)2003 LARC/USP");
        this.jlRodape.setVerticalAlignment(SwingConstants.TOP);
        this.jpTudo.add(this.jlRodape);

        getContentPane().add(this.jpTudo);
        this.jpTudo.setBounds(10, 500, 570, 20);

        pack();
    }//GEN-END:initComponents

    private void jbActiveOpenActionPerformed(ActionEvent evt)
    {
        String args[] = new String[6];
        args[0] = Decoder.bytePontoToIpSimulado(this.jtfHost.getText());
        args[1] = this.jtfPorta.getText();
        args[2] = this.jtaDadosEnviados.getText();
        args[3] = this.jtfTimeout.getText();
        args[4] = this.jtfTamJan.getText();
        args[5] = this.jtfTamSeg.getText();

        try
        {
            this.maquinaDeEstados.recebePrimitiva(TCP.P_ACTIVEOPEN, args);
            habilitaNovaConexao(false);            
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    private void jbPassiveOpenActionPerformed(ActionEvent evt)
    {
        String args[] = new String[6];
//        args[0] = Decoder.bytePontoToIpSimulado(this.jTextFieldHost.getText());
//        args[1] = this.jTextFieldPorta.getText();
        args[2] = this.jtaDadosEnviados.getText();
        args[3] = this.jtfTimeout.getText();
        args[4] = this.jtfTamJan.getText();
        args[5] = this.jtfTamSeg.getText();

        try
        {
            this.maquinaDeEstados.recebePrimitiva(TCP.P_PASSIVEOPEN, args);
            
            habilitaNovaConexao(false);            
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    } // jbPassiveOpen

    private void jbEnviarActionPerformed(ActionEvent evt)
    {
        // FIXME Implementar jbEnviar
    } // jbEnviar

    private void jbCloseActionPerformed(ActionEvent evt)
    {
        String args[] = new String[6];
        args[0] = Decoder.bytePontoToIpSimulado(this.jtfHost.getText());
        args[1] = this.jtfPorta.getText();
        args[2] = this.jtaDadosEnviados.getText();
        args[3] = this.jtfTimeout.getText();
        args[4] = this.jtfTamJan.getText();
        args[5] = this.jtfTamSeg.getText();
        
        try
        {
            this.maquinaDeEstados.recebePrimitiva(TCP.P_CLOSE, args);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    } // jbClose
       
    private void jtfPortaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextFieldPortaActionPerformed
    }//GEN-LAST:event_jTextFieldPortaActionPerformed

    private void jTextFieldEstAtualActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstAtualActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextFieldEstAtualActionPerformed

    private void jTextFieldTimeoutActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeoutActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeoutActionPerformed

    private void jTextFieldHostActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextFieldHostActionPerformed
    }//GEN-LAST:event_jTextFieldHostActionPerformed

    private void jbResetActionPerformed(ActionEvent evt)
    {
         JOptionPane.showMessageDialog(null,"TimeoutTX: O host não enviou resposta.");
    }
    
    /** Exit the Application */
    private void exitForm(WindowEvent evt)
    {
        this.dispose();
        this.maquinaDeEstados.getMonitor().fechaMaquinaDeEstados(this.idConexao);
    }
    
    /**
     * Atualiza os dados da área de texto da tabela do diagrama de tempo
     *
     * Exemplo:
     * MaquinaDeEstadosFrame mef = new MaquinaDeEstadosFrame();\
     * mef.atualizaDadosEstado("Closed", "Act.Open", "->", "(0,0,0,300)");   
     *
     *
     * @param _estado O novo estado da máquina de estados da conexão
     * @param _primitiva O tipo de primitiva que está sendo utilizada
     * @param _sentido A direção do segmento (enviado: -> ou recebido: <-)
     * @param _segmento O segmento (NS, Tam, NACK, T.Jan)
     */
    public void atualizaDadosEstado(String _estado, String _primitiva, 
        String _sentido, String _segmento)
    {
        this.jtaEstado.append(_estado + "\n");
        this.jtaPrimitiva.append(_primitiva + "\n");
        this.jtaSentido.append(_sentido + "\n");
        this.jtaDescricaoSegmento.append(_segmento + "\n");
        
        this.jtaEstado.setCaretPosition(this.jtaEstado.getDocument().getLength());
        this.jtaPrimitiva.setCaretPosition(this.jtaPrimitiva.getDocument().getLength());
        this.jtaSentido.setCaretPosition(this.jtaSentido.getDocument().getLength());
        this.jtaDescricaoSegmento.setCaretPosition(this.jtaDescricaoSegmento.getDocument().getLength());
    }
    
    /**
     * Atualiza na interface as informações sobre a conexão
     * 
     * Exemplo:
     * MaquinaDeEstadosFrame mef = new MaquinaDeEstadosFrame();
     * mef.atualizaInfoConexao("Established", "10.0.0.1:3123", "1211", "", "");
     *
     *
     * @param _estado O estado atual da máquina de estados da conexão
     * @param _IPSimuladoLocal O IP Simulado Local da Conexão
     * @param _portaLocal A porta local da conexão
     * @param _IPSimuladoRemoto O IP Simulado Remoto da Conexão
     * @param _portaRemota A porta remota da conexão
     */
    public void atualizaInfoConexao(byte _estado, String _IPSimuladoLocal,
        String _portaLocal, String _IPSimuladoRemoto, String _portaRemota)
    {
        
        StringBuffer buffer = new StringBuffer();
        
        if(_IPSimuladoLocal.length() > 0)
            buffer.append (TCP.nomeEstado[_estado] + ". ( " + 
                    _IPSimuladoLocal + ", " + _portaLocal);
        
        if(!_IPSimuladoRemoto.equals(""))
            buffer.append("; " + _IPSimuladoRemoto + ", " + _portaRemota +  " )");
        else
            buffer.append("; -, - )");
        
        this.jlInformacoesConexao.setText(buffer.toString());
        
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jbActiveOpen;
    private JButton jButtonAjuda;
    private JButton jbClose;
    private JButton jbEnviar;
    private JButton jbPassiveOpen;
    private JButton jbReset;
    private JLabel jlRodape;
    private JLabel jlDadosEnviados;
    private JLabel jlSegmento;
    private JLabel jlEstAtual;
    private JLabel jlEstado;
    private JLabel jlHost;
    private JLabel jlNumACK;
    private JLabel jlNumBytesEnviados;
    private JLabel jlNumSeq;
    private JLabel jlPorta;
    private JLabel jlPrimitiva;
    private JLabel jlSentido;
    private JLabel jlTamJan;
    private JLabel jlTamSeg;
    private JLabel jlTimeout;
    private JLabel jlInformacoesConexao;
    private JPanel jpConexao;
    private JPanel jpPrimitivas;
    private JPanel jpDiagramaTempo;
    private JPanel jpConf;
    private JPanel jpInfo;
    private JPanel jpDadosRecebidos;
    private JPanel jpTudo;
    private JScrollPane jspadosEnviados;
    private JScrollPane jspEstado;
    private JScrollPane jspPrimitiva;
    private JScrollPane jspSentido;
    private JScrollPane jspDescricaoSegmento;
    private JScrollPane jspDadosRecebidos;
    private JTextArea jtaDadosEnviados;
    private JTextArea jtaDadosRecebidos;
    private JTextArea jtaDescricaoSegmento;
    private JTextArea jtaEstado;
    private JTextArea jtaPrimitiva;
    private JTextArea jtaSentido;
    private JTextField jtfEstAtual;
    /** <code>jtfHost</code>: IPSimulado do host remoto */
    public JTextField jtfHost;
    private JTextField jtfNumACK;
    private JTextField jtfNumSeq;
    /** <code>jtfPorta</code>: Porta do host remoto */
    public JTextField jtfPorta;
    private JTextField jtfTamJan;
    private JTextField jtfTamSeg;
    private JTextField jtfTimeout;
    // End of variables declaration//GEN-END:variables
    private MaquinaDeEstados maquinaDeEstados;
    private int idConexao;
}
