/*
 * @(#)MaquinaDeEstadosFrame.java	1.0 31/04/2004
 *
 * Copyleft (L) 2004 Laboratório de Arquitetura e Redes de Computadores
 * Escola Politécnica da Universidade de São Paulo.
 *
 */
package br.usp.larc.tcp.aplicacao;


//import java.lang.reflect.Array;
//import java.util.ArrayList;

import br.usp.larc.tcp.protocolo.*;

//import java.awt.*;
//import java.awt.event.*;
import javax.swing.*;

/** 
 * Classe que representa a Interface HM Maquina de Estados.
 * Detalhes e dicas de implementação podem ser consultadas nas Apostilas.
 *
 * Procure sempre usar o paradigma Orientado a Objeto, a simplicidade e a 
 * criatividade na implementação do seu projeto.
 *  
 *
 * @author	Laboratório de Arquitetura e Redes de Computadores.
 * @version	1.0 Agosto 2003.
 */
public class MaquinaDeEstadosFrame extends javax.swing.JFrame {
    
    /** Creates new form MaquinaDeEstadosFrame */
//    public MaquinaDeEstadosFrame() {
//        initComponents();
//    }
    
    /** Creates new form Monitor */
    public MaquinaDeEstadosFrame(MaquinaDeEstados _maquinaDeEstados) {
        this.maquinaDeEstados = _maquinaDeEstados;
        this.initComponents(); 
        this.setSize(590,550);
        this.idConexao = _maquinaDeEstados.getIdConexao();
        this.setTitle("Máquina de Estado " + 
             this.idConexao  + " (IPSimul = " +
            _maquinaDeEstados.getIpSimuladoLocalBytePonto() + " : " +
            _maquinaDeEstados.getPortaLocal() + ")");
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        this.jPanel1 = new javax.swing.JPanel();
        this.jLabelnformacoesConexao = new javax.swing.JLabel();
        this.jPanel2 = new javax.swing.JPanel();
        this.jButtonActiveOpen = new javax.swing.JButton();
        this.jButtonPassiveOpen = new javax.swing.JButton();
        this.jButtonEnviar = new javax.swing.JButton();
        this.jButtonClose = new javax.swing.JButton();
        this.jLabelHost = new javax.swing.JLabel();
        this.jLabelPorta = new javax.swing.JLabel();
        this.jTextFieldHost = new javax.swing.JTextField();
        this.jTextFieldPorta = new javax.swing.JTextField();
        this.jLabelDadosEnviados = new javax.swing.JLabel();
        this.jLabelNumBytesEnviados = new javax.swing.JLabel();
        this.jScrollPane1 = new javax.swing.JScrollPane();
        this.jTextAreaDadosEnviados = new javax.swing.JTextArea();
        this.jPanel3 = new javax.swing.JPanel();
        this.jLabelEstado = new javax.swing.JLabel();
        this.jLabelPrimitiva = new javax.swing.JLabel();
        this.jLabelSegmento = new javax.swing.JLabel();
        this.jLabelDescricaoSegmento = new javax.swing.JLabel();
        this.jScrollPane2 = new javax.swing.JScrollPane();
        this.jTextAreaEstado = new javax.swing.JTextArea();
        this.jScrollPane3 = new javax.swing.JScrollPane();
        this.jTextAreaPrimitiva = new javax.swing.JTextArea();
        this.jScrollPane4 = new javax.swing.JScrollPane();
        this.jTextAreaSegmento = new javax.swing.JTextArea();
        this.jScrollPane5 = new javax.swing.JScrollPane();
        this.jTextAreaDescricaoSegmento = new javax.swing.JTextArea();
        this.jPanel4 = new javax.swing.JPanel();
        this.jButtonAjuda = new javax.swing.JButton();
        this.jButtonReset = new javax.swing.JButton();
        this.jLabelTimeout = new javax.swing.JLabel();
        this.jLabelTamJan = new javax.swing.JLabel();
        this.jLabelTamSeg = new javax.swing.JLabel();
        this.jTextFieldTimeout = new javax.swing.JTextField();
        this.jTextFieldTamJan = new javax.swing.JTextField();
        this.jTextFieldTamSeg = new javax.swing.JTextField();
        this.jPanel5 = new javax.swing.JPanel();
        this.jLabelEstAtual = new javax.swing.JLabel();
        this.jLabelNumSeq = new javax.swing.JLabel();
        this.jLabelNumACK = new javax.swing.JLabel();
        this.jTextFieldNumSeq = new javax.swing.JTextField();
        this.jTextFieldEstAtual = new javax.swing.JTextField();
        this.jTextFieldNumACK = new javax.swing.JTextField();
        this.jPanel6 = new javax.swing.JPanel();
        this.jScrollPane6 = new javax.swing.JScrollPane();
        this.jTextAreaDadosRecebidos = new javax.swing.JTextArea();
        this.jPanel7 = new javax.swing.JPanel();
        this.jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Conex\u00e3o", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 0, 12), java.awt.Color.red));
        jLabelnformacoesConexao.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jPanel1.add(jLabelnformacoesConexao);
        jLabelnformacoesConexao.setBounds(10, 20, 350, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 0, 370, 60);

        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Primitivas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 0, 12), java.awt.Color.red));
        jButtonActiveOpen.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jButtonActiveOpen.setText("ActiveOpen");
        jButtonActiveOpen.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonActiveOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonActiveOpen.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonActiveOpen.setEnabled(true);
        jPanel2.add(jButtonActiveOpen);
        jButtonActiveOpen.setBounds(10, 20, 80, 30);
        jButtonActiveOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActiveOpenActionPerformed(evt);
            }
        });
        
        jButtonPassiveOpen.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jButtonPassiveOpen.setText("PassiveOpen");
        jButtonPassiveOpen.setMaximumSize(new java.awt.Dimension(500, 500));
        jButtonPassiveOpen.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPassiveOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPassiveOpen.setEnabled(true);
        jPanel2.add(jButtonPassiveOpen);
        jButtonPassiveOpen.setBounds(10, 60, 100, 30);
        jButtonPassiveOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassiveOpenActionPerformed(evt);
            }
        });

        jButtonEnviar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.setEnabled(false);
        jButtonEnviar.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jPanel2.add(jButtonEnviar);
        jButtonEnviar.setBounds(140, 60, 100, 30);

        jButtonClose.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jButtonClose.setText("Close");
        jButtonClose.setEnabled(false);
        jButtonClose.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jButtonClose);
        jButtonClose.setBounds(260, 60, 100, 30);

        this.jLabelHost.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        this.jLabelHost.setText("Host");
        this.jPanel2.add(this.jLabelHost);
        this.jLabelHost.setBounds(100, 20, 30, 15);

        jLabelPorta.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelPorta.setText("Porta");
        jPanel2.add(jLabelPorta);
        jLabelPorta.setBounds(290, 20, 30, 16);
/*
        jTextFieldHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHostActionPerformed(evt);
            }
        });*/
        jPanel2.add(jTextFieldHost);
        jTextFieldHost.setBounds(130, 20, 160, 20);
/*
        jTextFieldPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPortaActionPerformed(evt);
            }
        });*/
        jPanel2.add(jTextFieldPorta);
        jTextFieldPorta.setBounds(320, 20, 40, 20);

        jLabelDadosEnviados.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelDadosEnviados.setText("Dados Enviados");
        jPanel2.add(jLabelDadosEnviados);
        jLabelDadosEnviados.setBounds(10, 90, 100, 15);

        jLabelNumBytesEnviados.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelNumBytesEnviados.setText("Número de byres enviados: 0");
        jPanel2.add(jLabelNumBytesEnviados);
        jLabelNumBytesEnviados.setBounds(140, 90, 180, 15);

        jScrollPane1.setViewportView(jTextAreaDadosEnviados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 104, 350, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(5, 60, 370, 190);

        jPanel3.setLayout(null);

        jPanel3.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Diagrama de Tempo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 0, 12), java.awt.Color.red));
        jLabelEstado.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelEstado.setText("Estado");
        jPanel3.add(jLabelEstado);
        jLabelEstado.setBounds(10, 20, 45, 15);

        jLabelPrimitiva.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelPrimitiva.setText("Primitiva");
        jPanel3.add(jLabelPrimitiva);
        jLabelPrimitiva.setBounds(100, 20, 60, 15);

        jLabelSegmento.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelSegmento.setText("Segmento");
        jPanel3.add(jLabelSegmento);
        jLabelSegmento.setBounds(170, 20, 60, 15);

        jLabelDescricaoSegmento.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelDescricaoSegmento.setText("(NS,Tam,NACK,Jan)");
        jPanel3.add(jLabelDescricaoSegmento);
        jLabelDescricaoSegmento.setBounds(230, 20, 130, 16);

        jScrollPane2.setViewportView(jTextAreaEstado);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 90, 200);

        jScrollPane3.setViewportView(jTextAreaPrimitiva);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(100, 40, 80, 200);

//        jTextAreaSegmento.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jScrollPane4.setViewportView(jTextAreaSegmento);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(180, 40, 40, 200);

        jScrollPane5.setViewportView(jTextAreaDescricaoSegmento);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(220, 40, 140, 200);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(5, 250, 370, 250);

        jPanel4.setLayout(null);

        jPanel4.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Configura\u00e7\u00f5es", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 0, 12), java.awt.Color.red));
        jButtonAjuda.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jButtonAjuda.setText("Ajuda");
        jButtonAjuda.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jButtonAjuda);
        jButtonAjuda.setBounds(10, 110, 80, 20);

        jButtonReset.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jButtonReset.setText("Reset");
        jButtonReset.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jPanel4.add(jButtonReset);
        jButtonReset.setBounds(120, 110, 70, 20);

        jLabelTimeout.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelTimeout.setText("Timeout (ms):");
        jPanel4.add(jLabelTimeout);
        jLabelTimeout.setBounds(10, 20, 130, 15);

        jLabelTamJan.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelTamJan.setText("Tam. Jan. (bytes):");
        jPanel4.add(jLabelTamJan);
        jLabelTamJan.setBounds(10, 50, 130, 15);

        jLabelTamSeg.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelTamSeg.setText("Tam. Seg (bytes):");
        jPanel4.add(jLabelTamSeg);
        jLabelTamSeg.setBounds(10, 80, 130, 15);

        jTextFieldTimeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimeoutActionPerformed(evt);
            }
        });

        jPanel4.add(jTextFieldTimeout);
        jTextFieldTimeout.setText("3000");
        jTextFieldTimeout.setBounds(140, 20, 50, 20);

        jPanel4.add(jTextFieldTamJan);
        jTextFieldTamJan.setText("300");
        jTextFieldTamJan.setBounds(140, 50, 50, 20);

        jPanel4.add(jTextFieldTamSeg);
        jTextFieldTamSeg.setText("100");
        jTextFieldTamSeg.setBounds(140, 80, 50, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(380, 0, 200, 140);

        jPanel5.setLayout(null);

        jPanel5.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Informa\u00e7\u00f5es", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 0, 12), java.awt.Color.red));
        jLabelEstAtual.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelEstAtual.setText("Est Atual (Tx/Rx)");
        jPanel5.add(jLabelEstAtual);
        jLabelEstAtual.setBounds(10, 20, 130, 15);

        jLabelNumSeq.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelNumSeq.setText("Nº Seq/Ult Conf");
        jPanel5.add(jLabelNumSeq);
        jLabelNumSeq.setBounds(10, 50, 130, 15);

        jLabelNumACK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12));
        jLabelNumACK.setText("Nº ACK");
        jPanel5.add(jLabelNumACK);
        jLabelNumACK.setBounds(10, 80, 130, 15);

        jPanel5.add(jTextFieldNumSeq);
        jTextFieldNumSeq.setBounds(140, 50, 50, 20);

        jTextFieldEstAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstAtualActionPerformed(evt);
            }
        });

        jPanel5.add(jTextFieldEstAtual);
        jTextFieldEstAtual.setBounds(140, 20, 50, 20);

        jPanel5.add(jTextFieldNumACK);
        jTextFieldNumACK.setBounds(140, 80, 50, 20);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(380, 140, 200, 110);

        jPanel6.setLayout(null);

        jPanel6.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Dados Recebidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 0, 12), java.awt.Color.red));
        jScrollPane6.setViewportView(jTextAreaDadosRecebidos);

        jPanel6.add(jScrollPane6);
        jScrollPane6.setBounds(10, 20, 180, 220);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(380, 250, 200, 250);

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("MEFrame - Powered by Java Technologies - Copyleft (L)2003 LARC/USP");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(jLabel1);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(10, 500, 570, 20);

        pack();
    }//GEN-END:initComponents

    private void jButtonActiveOpenActionPerformed(java.awt.event.ActionEvent evt)
    {
		System.out.println("jButtonActiveOpenActionPerformed: inicio");

        String args[] = new String[6];
        args[0] = Decoder.bytePontoToIpSimulado(this.jTextFieldHost.getText());
        args[1] = this.jTextFieldPorta.getText();
        args[2] = this.jTextAreaDadosEnviados.getText();
        args[3] = this.jTextFieldTimeout.getText();
        args[4] = this.jTextFieldTamJan.getText();
        args[5] = this.jTextFieldTamSeg.getText();

        try
        {
    		System.out.println("jButtonActiveOpenActionPerformed: recebePrimitiva");
            this.maquinaDeEstados.recebePrimitiva(ProtocoloTCP.P_ACTIVEOPEN, args);
            
    		System.out.println("jButtonActiveOpenActionPerformed: alteraDestino");
            this.maquinaDeEstados.getMonitor().getTabelaDeConexoes().alteraDestino(
                    this.maquinaDeEstados.getIdConexao(),
                    this.maquinaDeEstados.getIpSimuladoDestino(),
                    Integer.toString(this.maquinaDeEstados.getPortaDestino()));
            
    		System.out.println("jButtonActiveOpenActionPerformed: inatualizaInfoConexaoicio");
            this.atualizaInfoConexao(
                this.maquinaDeEstados.getEstadoMEConAtual(),
                this.maquinaDeEstados.getIpSimuladoLocalBytePonto(),
                Integer.toString(this.maquinaDeEstados.getPortaLocal()), 
                this.maquinaDeEstados.getIpSimuladoDestinoBytePonto(),
                Integer.toString(this.maquinaDeEstados.getPortaDestino())); 

    		System.out.println("jButtonActiveOpenActionPerformed: ajusta botões");
            this.jButtonClose.setEnabled(true);
            this.jButtonPassiveOpen.setEnabled(false);
            this.jButtonActiveOpen.setEnabled(false);
            this.jTextFieldHost.setEnabled(false);
            this.jTextFieldPorta.setEnabled(false);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
		System.out.println("jButtonActiveOpenActionPerformed: fim");
    }

    private void jButtonPassiveOpenActionPerformed(java.awt.event.ActionEvent evt)
    {
        String args[] = new String[6];
//        args[0] = Decoder.bytePontoToIpSimulado(this.jTextFieldHost.getText());
//        args[1] = this.jTextFieldPorta.getText();
        args[2] = this.jTextAreaDadosEnviados.getText();
        args[3] = this.jTextFieldTimeout.getText();
        args[4] = this.jTextFieldTamJan.getText();
        args[5] = this.jTextFieldTamSeg.getText();

        try
        {
            this.maquinaDeEstados.recebePrimitiva(ProtocoloTCP.P_PASSIVEOPEN, args);
/*            
            this.maquinaDeEstados.getMonitor().getTabelaDeConexoes().alteraDestino(
                    this.maquinaDeEstados.getIdConexao(),
                    this.maquinaDeEstados.getIpSimuladoDestino(),
                    Integer.toString(this.maquinaDeEstados.getPortaDestino()));
*/            
            this.atualizaInfoConexao(
                    this.maquinaDeEstados.getEstadoMEConAtual(),
                    this.maquinaDeEstados.getIpSimuladoLocalBytePonto(),
                    Integer.toString(this.maquinaDeEstados.getPortaLocal()), 
                    "null", "null");
            
            this.jButtonClose.setEnabled(true);
            this.jButtonPassiveOpen.setEnabled(false);
            this.jButtonActiveOpen.setEnabled(false);
            this.jTextFieldHost.setEnabled(false);
            this.jTextFieldPorta.setEnabled(false);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jTextFieldPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPortaActionPerformed
    }//GEN-LAST:event_jTextFieldPortaActionPerformed

    private void jTextFieldEstAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstAtualActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextFieldEstAtualActionPerformed

    private void jTextFieldTimeoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeoutActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeoutActionPerformed

    private void jTextFieldHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHostActionPerformed
    }//GEN-LAST:event_jTextFieldHostActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
         JOptionPane.showMessageDialog(null,"TimeoutTX: O host não enviou resposta.");
    }//GEN-LAST:event_jButtonResetActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
        this.maquinaDeEstados.getMonitor().fechaMaquinaDeEstados(this.idConexao);
    }//GEN-LAST:event_exitForm
    
    /*
     * Atualiza os dados da área de texto da tabela do diagrama de tempo
     *
     * Exemplo:
     * MaquinaDeEstadosFrame mef = new MaquinaDeEstadosFrame();\
     * mef.atualizaDadosEstado("Closed", "Act.Open", "->", "(0,0,0,300)");   
     *
     *
     * @param _estado O novo estado da máquina de estados da conexão
     * @param _primitiva O tipo de primitiva que está sendo utilizada
     * @param _direcao A direção do segmento (enviado: -> ou recebido: <-)
     * @param _segmento O segmento (NS, Tam, NACK, T.Jan)
     */
    public void atualizaDadosEstado(String _estado, String _primitiva, 
        String _direcao, String _segmento) {

        StringBuffer campo1 = new StringBuffer();
        StringBuffer campo2 = new StringBuffer();
        StringBuffer campo3 = new StringBuffer();
        StringBuffer campo4 = new StringBuffer();

        campo1.append(jTextAreaEstado.getText());
        campo1.append(_estado + "\n");
        jTextAreaEstado.setText(campo1.toString());

        campo2.append(jTextAreaPrimitiva.getText());
        campo2.append(_primitiva + "\n");
        jTextAreaPrimitiva.setText(campo2.toString());

        campo3.append(jTextAreaSegmento.getText());
        campo3.append(" " + _direcao + "\n");
        jTextAreaSegmento.setText(campo3.toString());

        campo4.append(jTextAreaDescricaoSegmento.getText());
        campo4.append(_segmento + "\n");
        jTextAreaDescricaoSegmento.setText(campo4.toString());
    }
    
    /*
     * Atualiza na interface as informações sobre a conexão
     * 
     * Exemplo:
     * MaquinaDeEstadosFrame mef = new MaquinaDeEstadosFrame();
     * mef.atualizaInfoConexao("Established", "10.0.0.1:3123", "1211", "", "");
     *
     *
     * @param _estado O estado atual da máquina de estados da conexão
     * @param _IPSimuladoLocal O IP Simulado Local da Conexão
     * @param _portaLocal A porta local da conexão
     * @param _IPSimuladoRemoto O IP Simulado Remoto da Conexão
     * @param _portaRemota A porta remota da conexão
     */
    public void atualizaInfoConexao(byte _estado, String _IPSimuladoLocal,
        String _portaLocal, String _IPSimuladoRemoto, String _portaRemota)
    {
        
        StringBuffer buffer = new StringBuffer();
        
        if(_IPSimuladoLocal.length() > 0)
            buffer.append (ProtocoloTCP.nomeEstado[_estado] + ". ( " + 
                    _IPSimuladoLocal + ", " + _portaLocal);
        
        if(!_IPSimuladoRemoto.equals(""))
            buffer.append("; " + _IPSimuladoRemoto + ", " + _portaRemota +  " )");
        else
            buffer.append("; -, - )");
        
        jLabelnformacoesConexao.setText(buffer.toString());
        
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActiveOpen;
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonPassiveOpen;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDadosEnviados;
    private javax.swing.JLabel jLabelDescricaoSegmento;
    private javax.swing.JLabel jLabelEstAtual;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelHost;
    private javax.swing.JLabel jLabelNumACK;
    private javax.swing.JLabel jLabelNumBytesEnviados;
    private javax.swing.JLabel jLabelNumSeq;
    private javax.swing.JLabel jLabelPorta;
    private javax.swing.JLabel jLabelPrimitiva;
    private javax.swing.JLabel jLabelSegmento;
    private javax.swing.JLabel jLabelTamJan;
    private javax.swing.JLabel jLabelTamSeg;
    private javax.swing.JLabel jLabelTimeout;
    private javax.swing.JLabel jLabelnformacoesConexao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextAreaDadosEnviados;
    private javax.swing.JTextArea jTextAreaDadosRecebidos;
    private javax.swing.JTextArea jTextAreaDescricaoSegmento;
    private javax.swing.JTextArea jTextAreaEstado;
    private javax.swing.JTextArea jTextAreaPrimitiva;
    private javax.swing.JTextArea jTextAreaSegmento;
    private javax.swing.JTextField jTextFieldEstAtual;
    public javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldNumACK;
    private javax.swing.JTextField jTextFieldNumSeq;
    public javax.swing.JTextField jTextFieldPorta;
    private javax.swing.JTextField jTextFieldTamJan;
    private javax.swing.JTextField jTextFieldTamSeg;
    private javax.swing.JTextField jTextFieldTimeout;
    // End of variables declaration//GEN-END:variables
    private MaquinaDeEstados maquinaDeEstados;
    private int idConexao;
}
